### ISSUE TITLE
你好可以开发wxid加好友吗？

### ISSUE THREAD

**Issue by LHC12580** [pwh-pwh/wxrecordread#10]
自己用不传播

**Comment by pwh-pwh** [comment]
微x模块已经有了

**Comment by LHC12580** [comment]
没用，被和谐了，需要大佬开发



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




 
微x模块已经有了

**Comment by pwh-pwh** [comment]
可以有偿定做

**Comment by LHC12580** [comment]
大佬，多少可以做一下，个人使用而已，不传播，规矩我懂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上8:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




 
可以有偿定做

**Comment by pwh-pwh** [comment]
tg联系

**Comment by LHC12580** [comment]
没找到，一个女生的头像？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上9:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




  
有频道吗？&nbsp;&nbsp;
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年9月6日(周三) 晚上9:04
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
 
tg联系
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
闰2月的群找我。我在里面。

**Comment by pwh-pwh** [comment]
> 没找到，一个女生的头像？
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年9月6日(周三) 晚上9:28
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
> 
> 
> 
> 
>   
> 有频道吗？&nbsp;&nbsp;
>  
> ---原始邮件---
>  发件人: @.&gt;
>  发送时间: 2023年9月6日(周三) 晚上9:04
>  收件人: @.&gt;;
>  抄送: @.@.&gt;;
>  主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
>  
> tg联系
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you authored the thread.Message ID: @.***&gt;
>   
> 闰2月的群找我。我在里面。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

李文这个id

**Comment by LHC12580** [comment]
麻烦你加一下吧，我发了二维码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




  
没找到，一个女生的头像？
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年9月6日(周三) 晚上9:28
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
 
有频道吗？&nbsp;&nbsp;
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年9月6日(周三) 晚上9:04
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
 
tg联系
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
 
闰2月的群找我。我在里面。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
李文这个id

**Comment by pwh-pwh** [comment]
哪呢

**Comment by pwh-pwh** [comment]
还在吗

**Comment by LHC12580** [comment]
在，但是一直联系不上，你有推特吗？推特试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上10:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




 
还在吗

**Comment by pwh-pwh** [comment]
> 在，但是一直联系不上，你有推特吗？推特试试
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年9月6日(周三) 晚上10:09
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
> 
> 
> 
> 
>  
> 还在吗
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Led1Jk我推

**Comment by LHC12580** [comment]
已经关注，大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




  
在，但是一直联系不上，你有推特吗？推特试试
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年9月6日(周三) 晚上10:09
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
 
还在吗
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Led1Jk我推

**Comment by LHC12580** [comment]
已经关注了哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




  
在，但是一直联系不上，你有推特吗？推特试试
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2023年9月6日(周三) 晚上10:09
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)
 
还在吗
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Led1Jk我推

**Comment by pwh-pwh** [comment]
同意了啊

**Comment by LHC12580** [comment]
好的，我看看，我已经关注了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月9日(周六) 凌晨0:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pwh-pwh/wxrecordread] 你好可以开发wxid加好友吗？ (Issue #10)




 
同意了啊
