### ISSUE TITLE
8.40可以用吗 

### ISSUE THREAD

**Issue by 239395** [pwh-pwh/wxrecordread#16]
可以做一个转账 也能看到微信ID的吗

**Comment by pwh-pwh** [comment]
> 可以做一个转账 也能看到微信ID的吗 

转账本来都是好友啊，可以看到的

**Comment by pwh-pwh** [comment]
> 可以做一个转账 也能看到微信ID的吗 

转账本来都是好友啊，可以看到的

**Comment by 239395** [comment]
姐 我指的是在微信转账界面可以看到  wxid  我看别人用抓包软件通过转账记录能抓到微信ID  因为有的人 微信好友删了 通过这个办法找到微信好友

**Comment by pwh-pwh** [comment]
> 姐 我指的是在微信转账界面可以看到  wxid  我看别人用抓包软件通过转账记录能抓到微信ID  因为有的人 微信好友删了 通过这个办法找到微信好友 

那就通过抓包软件搞就好，不在模块功能范围
