### ISSUE TITLE
能详细描述一下怎么修改聊天文字吗，为什么我的点聊天记录包可以获取wxid，但是怎么都不能出现修改文字的页面

### ISSUE THREAD

**Issue by zkzkok** [pwh-pwh/wxrecordread#18]

**Comment by pwh-pwh** [comment]
描述请提供微信版本和模块版本

**Comment by zkzkok** [comment]
微信版本实验了8.0.25，8.0.40
模块版本实验了[增加查看红包领取详情](https://github.com/pwh-pwh/wxrecordread/releases/tag/v3.3)
[修改文字消息支持8.40.0](https://github.com/pwh-pwh/wxrecordread/releases/tag/v2.1)
请问能详细描述一下怎么修改消息文字吗，我按照您图片上的点击私聊上方的用户名，但是就是呼不出修改的界面

**Comment by zkzkok** [comment]
作者大大方便的话能留个邮箱吗，有偿解决，不方便就算了

**Comment by zkzkok** [comment]
qq：1501125408
