### ISSUE TITLE
我如何知道群里用户发送了什么内容呢？

### ISSUE THREAD

**Issue by change3799** [pwh-pwh/wxrecordread#2]

**Comment by pwh-pwh** [comment]
弹出框后你点击确认就可以看到内容了呀，而且原来的内容可以看到名称，然后你复制到剪切板的名称和wxid就可以对应上来了呀

**Comment by change3799** [comment]
按钮还是处于灰色，闪退是怎么回事 ？

发自我的手机

**Comment by pwh-pwh** [comment]
你安装lsp了吗，然后模块作用域选择微信（其他的xp框架我没试过）

**Comment by pwh-pwh** [comment]
你用最新的v1.1版本看看

**Comment by change3799** [comment]
方便联系下你？ 还是闪退。

**Comment by change3799** [comment]
> 你用最新的v1.1版本看看

方便联系下你？还是闪退。

**Comment by pwh-pwh** [comment]
qq:2145865322 备注来意
