### ISSUE TITLE
源码编译出来之后不生效是怎么回事呢

### ISSUE THREAD

**Issue by Domlaa** [pwh-pwh/wxrecordread#4]
编译好之后根据使用说明试过了，结果没看到有显示弹窗，微信版本是8.0.23， LSPosed里也没有项目里的日志输出。

**Comment by pwh-pwh** [comment]
你先试一下[Releases](https://github.com/pwh-pwh/wxrecordread/releases)里面的安装包能不能用，你要重启下微信，然后打开合并好的聊天记录才能查看，按理说是没有问题的，如果连日志都没有输出，那有可能是模块没有启用生效

**Comment by pwh-pwh** [comment]
通过ddms跟踪调用堆栈或者定位ui之类的，然后反编译看看源码,hook函数查看这些入参出参
