### ISSUE TITLE
8.0.40微信获取不到

### ISSUE THREAD

**Issue by a1262293196** [pwh-pwh/wxrecordread#7]
![Screenshot_2023-08-31-13-11-29-382_com tencent mm](https://github.com/pwh-pwh/wxrecordread/assets/134761720/bd009459-e7c0-4ddd-803b-857da80ad9ef)

**Comment by pwh-pwh** [comment]
这个获取不到不是模块的原因，是因为微信本身把wxid隐藏了

**Comment by a1262293196** [comment]
那有什么办法获取嘛？

**Comment by pwh-pwh** [comment]
旧版本可以的，用8.0.25（然后模块也用回旧的），新的版本可能屏蔽了

**Comment by 1971338924** [comment]
啥时候更新一下老哥，期待8.40更新
