### ISSUE TITLE
请问可以增加其他模块入口吗？

### ISSUE THREAD

**Issue by 6ur9er** [pwh-pwh/wxrecordread#8]
![Screenshot_2023-09-03-22-32-29-755_com tencent mm-edit](https://github.com/pwh-pwh/wxrecordread/assets/103239502/9271df2c-dfc8-4941-9276-0d30f24cbc0e)
您好，您的模块和我正在使用的HaveFunPanel有所冲突，它将长按语音切换按钮做成了语音面板的按钮，即使不开启对应功能，也不能正常打开您的模块。请问您可以增加其他模块入口吗？比如长按顶部的联系人昵称，谢谢您

**Comment by pwh-pwh** [comment]
计划把消息修改的功能移动到模块界面进行修改，避免与其他模块冲突

**Comment by pwh-pwh** [comment]
感谢你的提议，已经更新了
https://github.com/pwh-pwh/wxrecordread/releases/tag/v2.2

**Comment by 6ur9er** [comment]
> 感谢你的提议，已经更新了
> https://github.com/pwh-pwh/wxrecordread/releases/tag/v2.2

感谢您能够接受我的提议

**Comment by 2096779623** [comment]
> 感谢你的提议，已经更新了 https://github.com/pwh-pwh/wxrecordread/releases/tag/v2.2

能更新一下readme里的截图吗？我试了很久都没按出来
