### ISSUE TITLE
8.0.40

### ISSUE THREAD

**Issue by Leisurely-Cloud** [pwh-pwh/wxrecordread#9]
打开合并聊天 显示wxid为 null

**Comment by pwh-pwh** [comment]
新版微信已经屏蔽这个wxid字段了，所以获取不到

**Comment by 1971338924** [comment]
老版本25的模块也是1.1为什么也不行啊老哥，还是获取不到

**Comment by pwh-pwh** [comment]
你试下让别人转发群聊天记录转发给你看一下，自己看不到自己转发的

**Comment by 1971338924** [comment]
我看的就是别人的😂



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 10:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pwh-pwh/wxrecordread] 8.0.40 (Issue #9)




 
你试下让别人转发群聊天记录转发给你看一下，自己看不到自己转发的

**Comment by 1971338924** [comment]
试了好几遍都不行，是不是规则又变了😂

**Comment by pwh-pwh** [comment]
不是规则变了，可能是对方也是新版微信的话，这个字段也会屏蔽掉，我猜，晚点我验证看看

**Comment by 1971338924** [comment]
好的感谢大佬



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 10:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pwh-pwh/wxrecordread] 8.0.40 (Issue #9)




 
不是规则变了，可能是对方也是新版微信的话，这个字段也会屏蔽掉，我猜，晚点我验证看看

**Comment by pwh-pwh** [comment]
我之前用8.25的转发合并的群聊天记录都是可以看id的

**Comment by 1971338924** [comment]
我今天挨个版本都试了😂只有修改记录好使



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 10:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pwh-pwh/wxrecordread] 8.0.40 (Issue #9)




 
我之前用8.25的转发合并的群聊天记录都是可以看id的

**Comment by 1971338924** [comment]
8.0.40有个别一两个可以获取到老哥，其他的多数获取不到怎么回事啊，就那一次获取出来了在就过去不出来了！
